// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odvaxzmdryyunpaiindp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kdmF4em1kcnl5dW5wYWlpbmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTIwNjcsImV4cCI6MjA3MjcyODA2N30.JbwE82Hkku3ASNuBt37yZ71ESCB1K6ihGY2veh5GCn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});